version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - url-shortener-network

  # Rust Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/urlshortener
      - SERVER_ADDRESS=0.0.0.0:3000
      - BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - url-shortener-network

  # SvelteKit Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: url_shortener_frontend
    environment:
      - PUBLIC_API_URL=http://localhost:3000
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  pg_data:
